# Preâmbulo Geral
project:
  type: book
  output-dir: docs
book:
  title: "**SEMEST UFPA 2024**"
  subtitle: "**DA FAXINA DE DADOS A RELATÓRIOS DINÂMICOS**"
  date: "11/20/2024"
  author:
    - name: "**Mário Diego Rocha Valente**"
      id: md
      orcid: 0000-0001-7262-3336
      url: mario.valente@detran.pa.gov.br
      email: mario.valente@detran.pa.gov.br
      corresponding: true
      affiliation:
        - Analista de Trânsito
        - DETRAN-PA
  page-footer:
    background: blue
    left: |
      (VALENTE - 2024).
    right: |
      UFPA.
  search: true
  repo-url: https://github.com/MarioDhiego
  repo-actions: [edit, issue]
  downloads: [pdf, docx]
  sharing: [twitter, facebook]
  page-navigation: true
  chapters:
    - index.qmd
    - Exploratoria.qmd
    - Regressao.qmd
    - Capitulo3.qmd
    - Capitulo4.qmd
    - Capitulo5.qmd
    - references.qmd
comments:
  hypothesis: true
title-block-banner: true 
bibliography: references.bib
format:
  html:
    code-fold: true
    code-tools: true
    code-link: true
    theme:
      light: [blue,custom.scss]
      dark:  [cyborg,custom.scss]
    toc: true
    number_sections: true
    toc_float: true
    toc-title: Índice
    toc-location: right
  pdf: 
    documentclass: report
  epub: default
    






